"""Small, dependency-free primitives for an agent economic assurance case."""

__version__ = "0.7.0"

from .adapters import (
    load_normalized_json_bundle,
    normalized_json_bundle,
    normalized_json_document,
    render_normalized_json,
)
from .assurance import (
    ASSURANCE_ENGINE_IMPLEMENTATION,
    DECISION_CONTRACT_SCHEMA,
    ROUTING_SEMANTICS,
    AssuranceEngine,
    decision_contract_digest,
    decision_contract_manifest,
    default_engine,
    evaluate,
    evaluate_bundle,
)
from .checks import DEFAULT_REQUIRED_COVERAGE, default_checks
from .claude_code import (
    ClaudeCodeSession,
    claude_code_bundle,
    claude_code_bundle_from_session,
    conversion_contract_template,
    conversion_receipt,
    inspect_claude_code_jsonl,
    inspect_to_contract_template,
    load_conversion_contract,
)
from .claude_code_tree import (
    claude_code_tree_bundle,
    claude_code_tree_bundle_from_session,
    inspect_claude_code_session_tree,
)
from .evidence import make_evidence_bundle
from .frontier import (
    ArmSummary,
    ExperimentPlan,
    FrontierCase,
    FrontierDecision,
    PairedComparison,
    clopper_pearson_upper,
    evaluate_frontier,
    load_experiment,
    load_plan,
    run_frontier,
)
from .frontier_report import (
    render_frontier_json,
    render_frontier_markdown,
    render_frontier_svg,
)
from .io import (
    load_baseline,
    load_csv_bundle,
    load_outcomes,
    load_policy,
    load_rates,
    load_traces,
)
from .models import (
    AssuranceCase,
    Baseline,
    CheckMode,
    CheckOutput,
    CheckResult,
    CheckSpec,
    CheckStatus,
    Coverage,
    Decision,
    EconomicPolicy,
    EvaluationView,
    EvidenceBundle,
    ModelRate,
    Outcome,
    TaskIdentity,
    TraceEvent,
)
from .otel_genai import (
    OtelGenAISession,
    conversion_contract_template as otel_genai_conversion_contract_template,
    conversion_receipt as otel_genai_conversion_receipt,
    inspect_otel_genai_json,
    otel_genai_bundle,
    otel_genai_bundle_from_session,
)

__all__ = [
    "ASSURANCE_ENGINE_IMPLEMENTATION",
    "DECISION_CONTRACT_SCHEMA",
    "DEFAULT_REQUIRED_COVERAGE",
    "ROUTING_SEMANTICS",
    "ArmSummary",
    "AssuranceCase",
    "AssuranceEngine",
    "Baseline",
    "CheckMode",
    "CheckOutput",
    "CheckResult",
    "CheckSpec",
    "CheckStatus",
    "ClaudeCodeSession",
    "Coverage",
    "Decision",
    "EconomicPolicy",
    "EvaluationView",
    "EvidenceBundle",
    "ExperimentPlan",
    "FrontierCase",
    "FrontierDecision",
    "ModelRate",
    "OtelGenAISession",
    "Outcome",
    "PairedComparison",
    "TaskIdentity",
    "TraceEvent",
    "__version__",
    "claude_code_bundle",
    "claude_code_bundle_from_session",
    "claude_code_tree_bundle",
    "claude_code_tree_bundle_from_session",
    "clopper_pearson_upper",
    "conversion_contract_template",
    "conversion_receipt",
    "decision_contract_digest",
    "decision_contract_manifest",
    "default_checks",
    "default_engine",
    "evaluate",
    "evaluate_bundle",
    "evaluate_frontier",
    "inspect_claude_code_jsonl",
    "inspect_claude_code_session_tree",
    "inspect_otel_genai_json",
    "inspect_to_contract_template",
    "load_baseline",
    "load_conversion_contract",
    "load_csv_bundle",
    "load_experiment",
    "load_normalized_json_bundle",
    "load_outcomes",
    "load_plan",
    "load_policy",
    "load_rates",
    "load_traces",
    "make_evidence_bundle",
    "normalized_json_bundle",
    "normalized_json_document",
    "otel_genai_bundle",
    "otel_genai_bundle_from_session",
    "otel_genai_conversion_contract_template",
    "otel_genai_conversion_receipt",
    "render_frontier_json",
    "render_frontier_markdown",
    "render_frontier_svg",
    "render_normalized_json",
    "run_frontier",
]
