"""Small, dependency-free primitives for an agent economic assurance case."""

from .adapters import load_normalized_json_bundle, normalized_json_bundle
from .assurance import AssuranceEngine, default_engine, evaluate, evaluate_bundle
from .checks import DEFAULT_REQUIRED_COVERAGE, default_checks
from .evidence import make_evidence_bundle
from .frontier import (
    ArmSummary,
    ExperimentPlan,
    FrontierCase,
    FrontierDecision,
    PairedComparison,
    clopper_pearson_upper,
    evaluate_frontier,
    load_experiment,
    load_plan,
    run_frontier,
)
from .frontier_report import (
    render_frontier_json,
    render_frontier_markdown,
    render_frontier_svg,
)
from .io import (
    load_baseline,
    load_csv_bundle,
    load_outcomes,
    load_policy,
    load_rates,
    load_traces,
)
from .models import (
    AssuranceCase,
    Baseline,
    CheckMode,
    CheckOutput,
    CheckResult,
    CheckSpec,
    CheckStatus,
    Coverage,
    Decision,
    EconomicPolicy,
    EvaluationView,
    EvidenceBundle,
    ModelRate,
    Outcome,
    TaskIdentity,
    TraceEvent,
)

__all__ = [
    "AssuranceCase",
    "AssuranceEngine",
    "ArmSummary",
    "Baseline",
    "CheckMode",
    "CheckOutput",
    "CheckResult",
    "CheckSpec",
    "CheckStatus",
    "Coverage",
    "DEFAULT_REQUIRED_COVERAGE",
    "Decision",
    "EconomicPolicy",
    "EvaluationView",
    "ExperimentPlan",
    "EvidenceBundle",
    "FrontierCase",
    "FrontierDecision",
    "ModelRate",
    "Outcome",
    "PairedComparison",
    "TaskIdentity",
    "TraceEvent",
    "default_checks",
    "default_engine",
    "clopper_pearson_upper",
    "evaluate",
    "evaluate_bundle",
    "evaluate_frontier",
    "load_baseline",
    "load_csv_bundle",
    "load_experiment",
    "load_normalized_json_bundle",
    "load_outcomes",
    "load_policy",
    "load_plan",
    "load_rates",
    "load_traces",
    "make_evidence_bundle",
    "normalized_json_bundle",
    "render_frontier_json",
    "render_frontier_markdown",
    "render_frontier_svg",
    "run_frontier",
]
